services: 
  haystack-api:
    image: "deepset/haystack:cpu"
    volumes:
      - ./:/opt/pipelines
      - ./rest_api/rest_api/pipeline:/opt/pipelines
    ports:
      - 8000:8000

    restart: on-failure

    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/opt/pipelines/document-search.haystack-pipeline.yml
      - TOKENIZERS_PARALLELISM=false

    depends_on:
      elasticsearch:
        condition: service_healthy
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
    ports:
      - '9200:9200'
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10

