topic_labels:
  - 'business'
  - 'entertainment'
  - 'politics'
  - 'sport'
  - 'tech'


embedding_model: 'sentence-transformers/all-MiniLM-L6-v2'
reader_model: 'deepset/tinyroberta-squad2'

retriever_top_k: 10
reader_top_k: 5

query_classifier_model: 'facebook/bart-large-mnli'

query_list: 
  - 'What kind of threat are Apples music jukebox iTunes facing?'
  - 'What device was named 2006s gadget of the year?'
  - 'Who won the New York Marathon in the last momments?'
  - 'Why was the release of the film about the Mumbai blasts in 1993 postponed?'
  - What is the latest news in the business category?
  - Who won the recent election in the politics category?
  - When was the last technology-related article published?
  - Who are the top-scoring players in the current sports season?
  - What is the most recent development in the entertainment industry?
  - Can you provide information on the stock market performance today?
  - What is the headline of the most recent article in the technology category?
  - When did the last major political event take place?
  - Tell me about the key figures in the current sports news.
  - What is the current state of the global economy?
  - Who are the leading actors in the latest movie release?
  - What's the recent news regarding climate change?
  - What's the most significant scientific discovery reported recently?
  # - Tell me about the top technology trends in 2023.
  # - Who won the last major sports event?
  # - What's the current situation in the entertainment industry?
  # - Provide details on the latest IPO in the business sector.
  # - Who is the CEO of the largest tech company right now?
  # - Explain the recent diplomatic conflict in the politics category.
  # - What are the trending fashion styles in 2023?
  # - What is the focus of the recent education news?
  # - Who is the leading scorer in the sports league this year?
  # - What is the latest innovation in the tech world?
  # - Can you summarize the current situation in the Middle East?
  # - Tell me about the recent achievements in space exploration.
  # - Explain the impact of recent regulations on the energy industry.
  # - What is the status of climate change agreements?
  # - Who are the key players in the gaming industry today?
  # - What is the most recent acquisition in the business world?
  # - Who won the Nobel Prize in literature this year?
  # - What is the current state of healthcare in the politics news?
  # - What are the emerging trends in food and cuisine?
  # - Provide information about the recent breakthroughs in medical research.
  # - Who is leading in the technology sector in terms of market share?
  # - What is the status of the latest trade negotiations?
  # - Explain the recent controversy in the entertainment world.
  # - What are the recent developments in automotive technology?
  # - Who are the candidates for the upcoming political election?
  # - Describe the recent performance of your favorite sports team.
  # - What is the most recent report on environmental conservation efforts?
  # - Who are the prominent figures in the fashion industry right now?
  # - Tell me about the recent developments in renewable energy.
  # - What is the current state of international relations?
  # - Explain the latest breakthroughs in artificial intelligence.
  # - Who are the major players in the e-commerce business today?
  # - What is the focus of the current healthcare reform discussions?
  # - What are the recent trends in home and interior design?
  # - Provide information on the recent advancements in robotics.
  # - Who are the leaders in the aerospace and aviation industry?
  # - What is the status of recent immigration policies in politics?
