# This file is used for the initialization of the class

topic_list:
  - 'computers'
  - 'vehicles'
  - 'sports'
  - 'classifieds'
  - 'politics'
  - 'religion'
topn_similar: 100
topic_model_type: 'bertopic'
clustering_type: 'kmeans'
cluster_count: 5
tf_model_path:
  - 'sentence-transformers/gtr-t5-base'
  - 'sentence-transformers/gtr-t5-large'
  - 'sentence-transformers/all-MiniLM-L6-v2'
  - 'sentence-transformers/all-MiniLM-L12-v2'
  - 'sentence-transformers/all-distilroberta-v1'
  - 'sentence-transformers/all-mpnet-base-v2'
multilingual: False
nlp_model_lib: 'gensim'
nlp_model_path: 'glove-wiki-gigaword-50'
dataset: '20NG'
dataset_prunning: 0.001
docs_df_path: "None"
topic_df_path: "None"

